[package]
name = "iced-tic-tac-toe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rust ui library following the elm architecture pattern
iced = "0.3.0"